/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wei_wanandroid_activity_ndk_JNIActivity */

#ifndef _Included_com_wei_wanandroid_activity_ndk_JNIActivity
#define _Included_com_wei_wanandroid_activity_ndk_JNIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wei_wanandroid_activity_ndk_JNIActivity
 * Method:    getAppID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wei_wanandroid_activity_ndk_JNIActivity_getAppID
  (JNIEnv *, jobject);

/*
 * Class:     com_wei_wanandroid_activity_ndk_JNIActivity
 * Method:    setAppID
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wei_wanandroid_activity_ndk_JNIActivity_setAppID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wei_wanandroid_activity_ndk_JNIActivity
 * Method:    invokeSuperClassMethodShowMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wei_wanandroid_activity_ndk_JNIActivity_invokeSuperClassMethodShowMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
